### ISSUE TITLE
您好，可以把开启步骤写详细一些嘛

### ISSUE THREAD

**Issue by Luuxcyz** [QIN2DIM/PigAI_GPT2#2]
您好，最近因为头疼批改网的作文无意间发现了您，也从一开始下载了python等软件，但还是不清楚怎么使用，driver都装好了，库也装好了，卡在最后一步不知道怎么办

**Comment by QIN2DIM** [comment]
请问是遇到了什么问题呢？ ⊙ω⊙

**Comment by Luuxcyz** [comment]
首先感谢您在百忙之中抽空回复我~因为我对python很陌生，照着您上面的步骤进行到最后一步代码就退出了，也没能运行下去，不知道问题出在那里，因为我文字的表达能力实在有限，这里恳请能要一下您的联系方式或者邮箱么，不会打扰到您，占用您的时间

**Comment by QIN2DIM** [comment]
在此留言即可。请提供具体的报错信息（截图），描述一下运行环境即可。应该不是什么大问题，调一调就能解决

**Comment by QIN2DIM** [comment]
emnmmm内容生成模型我还没开源- - -放在这的脚本是胡来的- - -只是为了欺骗批改网的打分系统的orz - -
