### ISSUE TITLE
请问大佬这个还能用吗

### ISSUE THREAD

**Issue by hailiuduantoufama** [QIN2DIM/PigAI_GPT2#5]
如题

**Comment by QIN2DIM** [comment]
我把 Model 撤回了，但应该仍然可用。

**Comment by hailiuduantoufama** [comment]
![image](https://user-images.githubusercontent.com/103260861/196412554-5d9dbd83-94fd-4e2c-b642-306db144edb7.png)
大佬能给下完整的项目吗，搞了很久弄不好还是，谢谢了！

**Comment by hailiuduantoufama** [comment]
可能是班级的问题，有的可以提交
![image](https://user-images.githubusercontent.com/103260861/196413372-0548f1bc-75e9-429f-a37a-338b22907ba0.png)
不太理解怎么回事
